version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db/:/var/lib/postgresql/data
    restart: always
    networks:
      - postgresnet
    env_file: ./.env.prod
    
  app:
    ports: 
      - "5000:8000"
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - ENVIRONMENT=production
    env_file: ./.env.prod
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - postgresnet
    restart: always
    command: sh start.sh

networks:
  postgresnet: